name: "BDA_Mask2Former_Dino_pretrained"
model_type: "MaskedEncoderDecoder"
encoder_type: "Dino"
decoder_type: "Mask2Former"
task: "BDA"
input:
  normalized_inputs: true
  mask_input: false
training:
  training_parameters:
    alpha: 0.25
    batch_size: 1
    gamma: 2
    grad_accumulation: 16
    l1_reg: 1.0e-09
    l2_reg: 1.0e-08
    log_images_every_n_steps: 100
    output_class_weights_strategy: "ipw"
    normalize_weights: False
    mask_x: 1024
    mask_y: 1024
    max_epochs: 1000
    optimizer_parameters:
      name: "AdamW"
      lr: 0.0005
      weight_decay: 0.0005
    output_class_weights:
      background: 1.0e-06
      destroyed: 23.706
      major damage: 9.852
      minor damage: 3.193
      no damage: 1.95
      un-classified: 35.23
    samples_per_epoch: 4000
    tile_x: 1024
    tile_y: 1024
    loss_parameters:
      loss: [["cross entropy", 1.0]]
      gamma: 2
      alpha: 0.25
      bins: 10
      momentum: 0.9
      smooth: 1.0e-06
validation:
  validation_parameters:
    validation_monitor: "val_macro_f1"
    validation_monitor_mode: "max"
    validation_checkpoint_save_top_k: 3
    validation_reduce_lr_on_plateau_cooldown: 3
    validation_reduce_lr_on_plateau_patience: 3
    batch_size: 1
model_parameters:
  encoder_parameters:
    freeze_backbone: False
    backbone: "dino"
    backbone_path: "/home/pperali/dinov3_vitl16_pretrain_sat493m-eadcf0ff.pth" # Change for local path