location_strategy: "centered"
location_parameters:
  sample_generator_process_pool_size: 6
  adjustment_buffer_distance_px: 326
presentation_strategy: "indexed"
dataset_adaptor_parameters:
  tile_x: 35
  tile_y: 35
  min_gsd_x: 0.005 # 0.5cm/px
  min_gsd_y: 0.005 # 0.5cm/px
  max_gsd_x: 0.5 # 50cm/px
  max_gsd_y: 0.5 # 50cm/px
  rescale_to_interval: True
  multiscale_steps: 2
  multiscale_step_interval: "logspace" # "linspace" or "logspace" 
  backend: "auto"
  mask_scale_strategy: "spatial"
  tile_scale_strategy: "spatial"
  rescale_strategy: "interpolate"
  generate_adjusted_geoms: True
annotator_parameters:
  generate_adjusted_sample_locations: True
  building_intersection_proportion_threshold: 0.0